spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${ALLOWED_REDIRECT_URIS}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: 30d  # 개발 환경에서는 30일로 길게 설정
  refresh-token-expire-time: 90d  # 개발 환경에서는 90일로 길게 설정

boost:
  oci:
    bucket: ${OCI_QA_BUCKET}
    namespace: ${OCI_NAMESPACE}
    region: ${OCI_REGION}
    credentials:
      access-key: ${OCI_ACCESS_KEY}
      secret-key: ${OCI_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,prometheus
  endpoint:
    health:
      show-details: always

webpush:
  vapid:
    public-key: ${VAPID_PUBLIC_KEY}
    private-key: ${VAPID_PRIVATE_KEY}

llm:
  prompt: ${LLM_PROMPT}
