spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: false

  datasource:
    url: ${PROD_DB_URL}

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${ALLOWED_REDIRECT_URIS}

jwt:
  secret: ${JWT_SECRET_KEY}

boost:
  oci:
    bucket: ${OCI_PROD_BUCKET}
    namespace: ${OCI_NAMESPACE}
    region: ${OCI_REGION}
    credentials:
      access-key: ${OCI_ACCESS_KEY}
      secret-key: ${OCI_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: boost-api
      env: prod
webpush:
  vapid:
    public-key: ${VAPID_PUBLIC_KEY}
    private-key: ${VAPID_PRIVATE_KEY}

llm:
  prompt: ${LLM_PROMPT}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
